apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - image: nginx
        name: frontend
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: frontend-claim0
        - mountPath: /etc/nginx/conf.d/site.conf
          name: frontend-claim1
      restartPolicy: Always
      volumes:
      - name: frontend-claim0
        persistentVolumeClaim:
          claimName: frontend-claim0
      - name: frontend-claim1
        persistentVolumeClaim:
          claimName: frontend-claim1
status: {}
