apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: ldap
  name: ldap
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ldap
    spec:
      containers:
      - env:
        - name: LDAP_ADMIN_PASSWORD
          value: aloja123
        - name: LDAP_DOMAIN
          value: arkhotech.com
        - name: LDAP_ORGANISATION
          value: Arkhotech SpA
        image: osixia/openldap:1.2.1
        name: ldap
        ports:
        - containerPort: 389
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: ldap
      restartPolicy: Always
      volumes:
      - name: ldap
        persistentVolumeClaim:
          claimName: ldap
status: {}
