apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - args:
        - php
        - artisan
        - queue:work
        - redis
        image: arkhotech/php-fpm:7.2
        name: worker
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: worker-claim0
      restartPolicy: Always
      volumes:
      - name: worker-claim0
        persistentVolumeClaim:
          claimName: worker-claim0
status: {}
