version: "3.3"

services:
  engine:
    depends_on: 
     - database
    image: arkhotech/python
    build:
      context: .
      dockerfile: python.dockerfile 
    volumes:
      - ./src:/app
    command: python engine/manage.py runserver 0.0.0.0:8000
    ports:
      - 80:8000
    networks:
      - frontend
      - backend
  database:
    image: "mysql:5.7.22"
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "aloja123"
      MYSQL_DATABASE: "engine"
      MYSQL_USER: "workflow"
      MYSQL_PASSWORD: "workflow123"

networks:
  frontend:
    driver: bridge 
  backend:
    driver: bridge

volumes:
  data:
