version: "0"

workflows:
  - name: "test"
    description: "test"
    activities:
      A1: 
        type: "init"
        transitions:
          - name: t1
            next: B1
            condition: "params == 1"
            default: true
          - name: t2
            next: B2
            condition: "params == 2"
      B1:
        type: "end"
        transitions:
          - name: tb1
            next: F1
            condition: "params == 1"
            default: true
          - name: tb2
            next: F2
            condition: "params == 5"
      B2: 
        type: "activity"
        action:
          - lamdbda: call(asdfasdfadsfa)
      F1:
        type: "end"
      F2:
        type: "end"