version: "0"

workflows:
  - name: "test2"
    description: "test"
    activities:
      A1: 
        type: "init"
        execution_type: synch   #async|sync
        actions:
          - type: "CallLambda"
            input:  # dela entrada toma los valores a y b
              - a: 1
              - b: 2
            output: "porcentaje"   # estas variables se van acumulando en cada salida
          - type: "Webhook"
            body: 
              {
                "a" : 1
              }
            headers:
              - content-type: "text/plain"
            ouput: "data"
          - type: "Evaluate"
            input:  #parametros de entrada 
              - params: "$procentaje" #referencia a un valor de la entrada
            operation: params * 5 +45
            output:  "resulr"  #Nombre de la salida
        callback:
          with_response: #"respuesta" #busca este ekemento dentro de la respuesta
            validate:  "fields a, b, c"  #complejo
        transitions:
          - name: t1
            next: B1
            condition: "params == 1"
            default: true
          - name: t2
            next: B2
            condition: "params == 2"
      B1:
        type: "end"
        transitions:
          - name: tb1
            next: F1
            condition: "params == 1"
            default: true
          - name: tb2
            next: F2
            condition: "params == 5"
      B2: 
        type: "activity"
        action:
          - lamdbda: call(asdfasdfadsfa)
      F1:
        type: "end"
      F2:
        type: "end"